### ISSUE TITLE
Is 'protobuf==3.0.0b3' necessary?

### ISSUE THREAD

**Issue by kkdd** [dezhin/osmread#13]
Hello,
Is following necessary in setup.py?

```python
if sys.version_info > (3,):
    requirements.append('protobuf==3.0.0b3')
```

**Comment by AndreyGurevich** [comment]
Any news here?

**Comment by kkdd** [comment]
I have realized that it is already solved by https://github.com/dezhin/osmread/pull/15.

**Comment by AndreyGurevich** [comment]
But just yesterday `pip install osmread` wanted protobuf==3.0.0b3. It is version 0.2, released 9 Apr 2017. Can you update the package in PyPi?

**Comment by kkdd** [comment]
I'm sorry to say that I can't update it in PyPi.
Can you install/update via ```git clone``` or ```pip install git+https://github.com/dezhin/osmread```?
